'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
'-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
'''<summary>
'''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class strings_en_US
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Raffy_Timelapse.strings_en_US", GetType(strings_en_US).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die All picture files ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_AllPicturefiles() As String
        Get
            Return ResourceManager.GetString("_General_AllPicturefiles", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_cancel() As String
        Get
            Return ResourceManager.GetString("_General_cancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_close() As String
        Get
            Return ResourceManager.GetString("_General_close", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_error() As String
        Get
            Return ResourceManager.GetString("_General_error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die file ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_file() As String
        Get
            Return ResourceManager.GetString("_General_file", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die files ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_files() As String
        Get
            Return ResourceManager.GetString("_General_files", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_info() As String
        Get
            Return ResourceManager.GetString("_General_info", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Czech ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_cs_CZ() As String
        Get
            Return ResourceManager.GetString("_General_language_cs_CZ", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_de_DE() As String
        Get
            Return ResourceManager.GetString("_General_language_de_DE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_en_US() As String
        Get
            Return ResourceManager.GetString("_General_language_en_US", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die French ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_fr_FR() As String
        Get
            Return ResourceManager.GetString("_General_language_fr_FR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Portuguese ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_pt_PT() As String
        Get
            Return ResourceManager.GetString("_General_language_pt_PT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_ok() As String
        Get
            Return ResourceManager.GetString("_General_ok", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Please wait... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_wait() As String
        Get
            Return ResourceManager.GetString("_General_wait", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_warning() As String
        Get
            Return ResourceManager.GetString("_General_warning", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property About() As String
        Get
            Return ResourceManager.GetString("About", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Version: ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property About_version() As String
        Get
            Return ResourceManager.GetString("About_version", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Credits ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Credits() As String
        Get
            Return ResourceManager.GetString("Credits", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Translators ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Credits_lbl_translators_head() As String
        Get
            Return ResourceManager.GetString("Credits_lbl_translators_head", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die You are getting redirected to the website of the content creator. Would you like to continue? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Credits_link() As String
        Get
            Return ResourceManager.GetString("Credits_link", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help() As String
        Get
            Return ResourceManager.GetString("Help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Direct Contact ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_gb_contact() As String
        Get
            Return ResourceManager.GetString("Help_gb_contact", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Online Support ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_gb_support() As String
        Get
            Return ResourceManager.GetString("Help_gb_support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Wiki ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_gb_wiki() As String
        Get
            Return ResourceManager.GetString("Help_gb_wiki", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Please only contact us via e-mail if the ticket system doesn&apos;t meet your request requirements. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_lbl_contact() As String
        Get
            Return ResourceManager.GetString("Help_lbl_contact", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die The preferred way to get support for Raffy Timelapse is to create a ticket online on GitHub. We have different ticket systems for different requirements.
    '''
    '''Please create a ticket if you found a bug, have a feature request or have any other question concerning Raffy Timelapse! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_lbl_support() As String
        Get
            Return ResourceManager.GetString("Help_lbl_support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Learn how to get started with Raffy Timelapse in our online Wiki. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_lbl_wiki() As String
        Get
            Return ResourceManager.GetString("Help_lbl_wiki", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Create a ticket ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_llbl_support() As String
        Get
            Return ResourceManager.GetString("Help_llbl_support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse Wiki ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_llbl_wiki() As String
        Get
            Return ResourceManager.GetString("Help_llbl_wiki", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importing Images ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Import() As String
        Get
            Return ResourceManager.GetString("Import", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importing image ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Import_lbl_progress1() As String
        Get
            Return ResourceManager.GetString("Import_lbl_progress1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die of ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Import_lbl_progress2() As String
        Get
            Return ResourceManager.GetString("Import_lbl_progress2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importing images... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ImportProgressInfo() As String
        Get
            Return ResourceManager.GetString("ImportProgressInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_del() As String
        Get
            Return ResourceManager.GetString("Main_btn_del", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Browse ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_drop() As String
        Get
            Return ResourceManager.GetString("Main_btn_drop", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Move Down ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_MoveDwn() As String
        Get
            Return ResourceManager.GetString("Main_btn_MoveDwn", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Move Up ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_MoveUp() As String
        Get
            Return ResourceManager.GetString("Main_btn_MoveUp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Multiselect ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_MultiSelect() As String
        Get
            Return ResourceManager.GetString("Main_btn_MultiSelect", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_start() As String
        Get
            Return ResourceManager.GetString("Main_btn_start", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Error: The timelapse couldn&apos;t be exported successfully. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress__1() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_-1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Error: Memory allocation failure. Try using a lower resolution. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress__2() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_-2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die The computer is being prepared... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_1() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Copying files... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_10() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_10", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Finished! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_100() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_100", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Film is beeing created, this may take a while... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_40() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_40", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Converting film, this may take a while... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_75() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_75", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Edit Picture ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_gb_PictureEdit() As String
        Get
            Return ResourceManager.GetString("Main_gb_PictureEdit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die All images must have the same resolution as the first imported image ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_DifferentResolution() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_DifferentResolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Error for {0}:  ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_error() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die No images imported ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_NoPictures() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_NoPictures", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Filetype is not supported ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_UnsupportedFiletype() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_UnsupportedFiletype", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Drop your Images here or browse for files ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_lbl_drop() As String
        Get
            Return ResourceManager.GetString("Main_lbl_drop", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Preview ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_lbl_preview() As String
        Get
            Return ResourceManager.GetString("Main_lbl_preview", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Timeline ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_lbl_timeline() As String
        Get
            Return ResourceManager.GetString("Main_lbl_timeline", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about() As String
        Get
            Return ResourceManager.GetString("Main_ms_about", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die About the software ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_about() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_about", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Credits ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_credits() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_credits", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_settings() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_settings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_update() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_update", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file() As String
        Get
            Return ResourceManager.GetString("Main_ms_file", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_exit() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_exit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Import Images ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_import() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_import", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_new() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_new", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Project... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_new_project() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_new_project", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Window... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_new_window() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_new_window", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_help() As String
        Get
            Return ResourceManager.GetString("Main_ms_help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_help_help() As String
        Get
            Return ResourceManager.GetString("Main_ms_help_help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Support Us ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_help_SupportUs() As String
        Get
            Return ResourceManager.GetString("Main_ms_help_SupportUs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Would you really like to close this window? All unsaved changes will be lost. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_closing() As String
        Get
            Return ResourceManager.GetString("Main_msg_closing", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse couldn&apos;t find the &apos;FFmpeg.exe&apos; on your computer, which is needed to use this program. Would you like to download the missing file? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_ffmpeg() As String
        Get
            Return ResourceManager.GetString("Main_msg_ffmpeg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete all selected images? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_MultiDelete() As String
        Get
            Return ResourceManager.GetString("Main_msg_MultiDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Would you really like to create a new project? All unsaved changes will be lost. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_NewProject() As String
        Get
            Return ResourceManager.GetString("Main_msg_NewProject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete the image [%1]? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_SingleDelete() As String
        Get
            Return ResourceManager.GetString("Main_msg_SingleDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Help us translating ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation() As String
        Get
            Return ResourceManager.GetString("Participation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse is a free program and will always stay this way. We don&apos;t want to ask you for money either. But if you want to support us, and speak a language that we don&apos;t speak, then please help us to translate this programm into other languages. It&apos;s free and very simple! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation_lbl_desc() As String
        Get
            Return ResourceManager.GetString("Participation_lbl_desc", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Translate the App ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation_lbl_head() As String
        Get
            Return ResourceManager.GetString("Participation_lbl_head", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Translate Now! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation_lbl_link() As String
        Get
            Return ResourceManager.GetString("Participation_lbl_link", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Processing ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProgressInfo() As String
        Get
            Return ResourceManager.GetString("ProgressInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die View log... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProgressInfo_lbl_errorlog() As String
        Get
            Return ResourceManager.GetString("ProgressInfo_lbl_errorlog", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Project Settings ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings() As String
        Get
            Return ResourceManager.GetString("ProjectSettings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Browse ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_btn_browse() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_btn_browse", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die High quality, low processing speed ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_quality_hq() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_quality_hq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Low quality, high processing speed ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_quality_lq() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_quality_lq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Medium quality and processing speed ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_quality_mq() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_quality_mq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Same as Input ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_resolution_OriginalResolution() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_resolution_OriginalResolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Frames per Second (FPS) ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_fps() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_fps", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Quality/Processing Speed ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_quality() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_quality", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Resolution ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_resolution() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_resolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Save to... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_SaveTo() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_SaveTo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die The specified path doesn&apos;t exist. Please verify that your export path is correct. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_InvalidPath() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_InvalidPath", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Please select the Frames per Second (FPS). ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_NoFps() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_NoFps", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Please select a resolution. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_NoResolution() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_NoResolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Please select a proportion between Quality and processing speed. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_quality() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_quality", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die The imported pictures have a lower resolution than the video export resolution. Please select another resolution. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_undersize() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_undersize", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings() As String
        Get
            Return ResourceManager.GetString("Settings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_gb_general() As String
        Get
            Return ResourceManager.GetString("Settings_gb_general", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Key Assignment ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_gb_keys() As String
        Get
            Return ResourceManager.GetString("Settings_gb_keys", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Check for Updates on start-up ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_general_cb_AutoUpdate() As String
        Get
            Return ResourceManager.GetString("Settings_general_cb_AutoUpdate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_general_lbl_language() As String
        Get
            Return ResourceManager.GetString("Settings_general_lbl_language", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die 2+8 (Numpad),W+S,Z+S ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_keys_cb_MoveImg() As String
        Get
            Return ResourceManager.GetString("Settings_keys_cb_MoveImg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Move images up and down ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_keys_lbl_MoveImg() As String
        Get
            Return ResourceManager.GetString("Settings_keys_lbl_MoveImg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update() As String
        Get
            Return ResourceManager.GetString("Update", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_btn_update() As String
        Get
            Return ResourceManager.GetString("Update_btn_update", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Changelog ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_lbl_changelog() As String
        Get
            Return ResourceManager.GetString("Update_lbl_changelog", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die This version: ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_lbl_LocalVersion() As String
        Get
            Return ResourceManager.GetString("Update_lbl_LocalVersion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Latest version: ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_lbl_NewestVersion() As String
        Get
            Return ResourceManager.GetString("Update_lbl_NewestVersion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse will be closed automatically to install the update. All unsaved changes will be lost. Do you want to continue? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_msg_close() As String
        Get
            Return ResourceManager.GetString("Update_msg_close", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die The Raffy Timelapse Updater couldn&apos;t be found on your computer. Please download the latest version manually online. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_msg_UpdaterNotFound() As String
        Get
            Return ResourceManager.GetString("Update_msg_UpdaterNotFound", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die No connection to the update servers. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress_1() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress-1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Searching for updates... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress0() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress0", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die You are already using the latest version! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress1() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Loading details of new version... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress2() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress2", resourceCulture)
        End Get
    End Property
End Class
