'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
'-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
'''<summary>
'''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class strings_de_DE
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Raffy_Timelapse.strings_de_DE", GetType(strings_de_DE).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Alle Bilddateien ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_AllPicturefiles() As String
        Get
            Return ResourceManager.GetString("_General_AllPicturefiles", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_cancel() As String
        Get
            Return ResourceManager.GetString("_General_cancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_close() As String
        Get
            Return ResourceManager.GetString("_General_close", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_error() As String
        Get
            Return ResourceManager.GetString("_General_error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_file() As String
        Get
            Return ResourceManager.GetString("_General_file", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Dateien ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_files() As String
        Get
            Return ResourceManager.GetString("_General_files", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_info() As String
        Get
            Return ResourceManager.GetString("_General_info", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_de_DE() As String
        Get
            Return ResourceManager.GetString("_General_language_de_DE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Englisch ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_en_US() As String
        Get
            Return ResourceManager.GetString("_General_language_en_US", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Portugiesisch ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_pt_PT() As String
        Get
            Return ResourceManager.GetString("_General_language_pt_PT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_ok() As String
        Get
            Return ResourceManager.GetString("_General_ok", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Bitte warten... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_wait() As String
        Get
            Return ResourceManager.GetString("_General_wait", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Warnung ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_warning() As String
        Get
            Return ResourceManager.GetString("_General_warning", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Über ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property About() As String
        Get
            Return ResourceManager.GetString("About", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Version: ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property About_version() As String
        Get
            Return ResourceManager.GetString("About_version", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Credits ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Credits() As String
        Get
            Return ResourceManager.GetString("Credits", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Du wirst auf die Website des Urhebers weitergeleitet. Möchtest du forfahren? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Credits_link() As String
        Get
            Return ResourceManager.GetString("Credits_link", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help() As String
        Get
            Return ResourceManager.GetString("Help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Direkter Kontakt ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_gb_contact() As String
        Get
            Return ResourceManager.GetString("Help_gb_contact", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Online Support ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_gb_support() As String
        Get
            Return ResourceManager.GetString("Help_gb_support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Wiki ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_gb_wiki() As String
        Get
            Return ResourceManager.GetString("Help_gb_wiki", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Bitte kontaktiere uns nur per E-Mail, wenn das Ticketsystem für deine Anfrage unpassend ist. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_lbl_contact() As String
        Get
            Return ResourceManager.GetString("Help_lbl_contact", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Die bevorzugte Supportvariante für Raffy Timelapse bildet unser Ticketsystem auf GitHub. Wir haben Ticketsysteme für verschiedene Kategorien.
    '''
    '''Bitte erstelle ein Ticket, wenn du einen Fehler gefunden hast, einen Funktionswunsch mit uns teilen möchtest oder sonstige Fragen hast. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_lbl_support() As String
        Get
            Return ResourceManager.GetString("Help_lbl_support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Erlerne den Umgang mit Raffy Timelapse anhand unseres Online Wikis. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_lbl_wiki() As String
        Get
            Return ResourceManager.GetString("Help_lbl_wiki", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Erstelle ein Ticket ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_llbl_support() As String
        Get
            Return ResourceManager.GetString("Help_llbl_support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse Wiki ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_llbl_wiki() As String
        Get
            Return ResourceManager.GetString("Help_llbl_wiki", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importiere Bilder ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Import() As String
        Get
            Return ResourceManager.GetString("Import", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importiere Bild ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Import_lbl_progress1() As String
        Get
            Return ResourceManager.GetString("Import_lbl_progress1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die von ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Import_lbl_progress2() As String
        Get
            Return ResourceManager.GetString("Import_lbl_progress2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importiere Bilder... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ImportProgressInfo() As String
        Get
            Return ResourceManager.GetString("ImportProgressInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_del() As String
        Get
            Return ResourceManager.GetString("Main_btn_del", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Durchsuchen ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_drop() As String
        Get
            Return ResourceManager.GetString("Main_btn_drop", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Nach Unten ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_MoveDwn() As String
        Get
            Return ResourceManager.GetString("Main_btn_MoveDwn", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Nach Oben ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_MoveUp() As String
        Get
            Return ResourceManager.GetString("Main_btn_MoveUp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Multiselektion ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_MultiSelect() As String
        Get
            Return ResourceManager.GetString("Main_btn_MultiSelect", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_start() As String
        Get
            Return ResourceManager.GetString("Main_btn_start", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Error: Es ist ein Fehler aufgetreten, die Zeitraffer-Aufnahme konnte nicht erfolgreich exportiert werden. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress__1() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_-1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Error: Memory allocation failure. Versuche eine niedrigere Auflösung. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress__2() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_-2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Der Computer wird vorbereitet... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_1() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Bilder werden kopiert... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_10() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_10", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Fertig! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_100() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_100", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Film wird erstellt, dies kann etwas Zeit in Anspruch nehmen... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_40() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_40", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Der Film wird in das ausgewählte Dateiformat konvertiert... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_75() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_75", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Bild bearbeiten ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_gb_PictureEdit() As String
        Get
            Return ResourceManager.GetString("Main_gb_PictureEdit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Alle Bilder müssen aus dem gleichen Verzeichnis stammen, wie das zuerst importierte. Bitte vergewissere dich, dass alle zu importierenden Bilder in dem selben Ordner sind. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_DifferentPath() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_DifferentPath", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Alle Bilder müssen die gleiche Auflösung haben, wie das zuerst importierte ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_DifferentResolution() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_DifferentResolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Es wurden keine Bilder importiert ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_NoPictures() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_NoPictures", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Dateityp wird nicht unterstützt ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_UnsupportedFiletype() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_UnsupportedFiletype", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Bilder hierher ziehen oder den PC durchsuchen ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_lbl_drop() As String
        Get
            Return ResourceManager.GetString("Main_lbl_drop", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Vorschau ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_lbl_preview() As String
        Get
            Return ResourceManager.GetString("Main_lbl_preview", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Timeline ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_lbl_timeline() As String
        Get
            Return ResourceManager.GetString("Main_lbl_timeline", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Über ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about() As String
        Get
            Return ResourceManager.GetString("Main_ms_about", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Über die Software ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_about() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_about", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Credits ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_credits() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_credits", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_settings() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_settings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_update() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_update", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file() As String
        Get
            Return ResourceManager.GetString("Main_ms_file", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_exit() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_exit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Bilder importieren ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_import() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_import", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Neu ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_new() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_new", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Projekt... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_new_project() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_new_project", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Fenster... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_new_window() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_new_window", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_help() As String
        Get
            Return ResourceManager.GetString("Main_ms_help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Hilfe/Support ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_help_help() As String
        Get
            Return ResourceManager.GetString("Main_ms_help_help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Unterstütze uns ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_help_SupportUs() As String
        Get
            Return ResourceManager.GetString("Main_ms_help_SupportUs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Möchtest du das Programm wirklich schließen? Alle nicht gespeicherten Änderungen gehen dadurch verloren. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_closing() As String
        Get
            Return ResourceManager.GetString("Main_msg_closing", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse konnte die Datei &apos;FFmpeg.exe&apos; nicht finden, welche für das Programm benötigt wird. Möchtest du diese Datei nun downloaden? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_ffmpeg() As String
        Get
            Return ResourceManager.GetString("Main_msg_ffmpeg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Bist du sicher, dass du die ausgewählten Bilder entfernen möchtest? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_MultiDelete() As String
        Get
            Return ResourceManager.GetString("Main_msg_MultiDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Möchtest du wirklich ein neues Projekt erstellen? Alle nicht gespeicherten Änderungen gehen dadurch verloren. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_NewProject() As String
        Get
            Return ResourceManager.GetString("Main_msg_NewProject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Bist du sicher, dass du das Bild [%1] entfernen möchtest? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_SingleDelete() As String
        Get
            Return ResourceManager.GetString("Main_msg_SingleDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Hilf uns beim Übersetzen ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation() As String
        Get
            Return ResourceManager.GetString("Participation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse ist ein kostenloses Programm und wird dies auch bleiben. Desweiteren möchten wir nicht nach Geld fragen. Stattdessen gibt es eine andere Möglichkeit uns zu unterstützen: das Programm für weltweite Nutzer in andere Sprachen übersetzen. Es geht ganz einfach! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation_lbl_desc() As String
        Get
            Return ResourceManager.GetString("Participation_lbl_desc", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Unterstütze uns ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation_lbl_head() As String
        Get
            Return ResourceManager.GetString("Participation_lbl_head", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Jetzt übersetzen! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation_lbl_link() As String
        Get
            Return ResourceManager.GetString("Participation_lbl_link", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Verarbeitung ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProgressInfo() As String
        Get
            Return ResourceManager.GetString("ProgressInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Log ansehen... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProgressInfo_lbl_errorlog() As String
        Get
            Return ResourceManager.GetString("ProgressInfo_lbl_errorlog", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Projekt-Einstellungen ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings() As String
        Get
            Return ResourceManager.GetString("ProjectSettings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Durchsuchen ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_btn_browse() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_btn_browse", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Hohe Qualität, langsame Verarbeitungzeit ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_quality_hq() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_quality_hq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Geringe Qualität, schnelle Verarbeitungszeit ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_quality_lq() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_quality_lq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Durchschnittliche Qualität und Verarbeitungszeit ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_quality_mq() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_quality_mq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Originalgröße ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_resolution_OriginalResolution() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_resolution_OriginalResolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Bilder pro Sekunde (FPS) ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_fps() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_fps", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Qualität/Geschwindigkeit ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_quality() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_quality", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Auflösung ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_resolution() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_resolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Speicherort ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_SaveTo() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_SaveTo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Der angegebene Pfad existiert nicht, bitte überprüfe deine Angaben. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_InvalidPath() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_InvalidPath", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Bitte wähle die Bilder pro Sekunde (FPS) aus. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_NoFps() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_NoFps", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Bitte wähle eine Auflösung aus. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_NoResolution() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_NoResolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Bitte wähle das Verhältnis zwischen Qualität und Geschwindigkeit aus. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_quality() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_quality", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Die ausgewählten Bilder sind zu klein für das ausgewählte Filmformat. Bitte wähle eine kleinere Auflösung. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_undersize() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_undersize", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings() As String
        Get
            Return ResourceManager.GetString("Settings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Allgemein ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_gb_general() As String
        Get
            Return ResourceManager.GetString("Settings_gb_general", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Tastenbelegung ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_gb_keys() As String
        Get
            Return ResourceManager.GetString("Settings_gb_keys", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Beim Programmstart nach Updates suchen ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_general_cb_AutoUpdate() As String
        Get
            Return ResourceManager.GetString("Settings_general_cb_AutoUpdate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_general_lbl_language() As String
        Get
            Return ResourceManager.GetString("Settings_general_lbl_language", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die 2+8 (Numpad),W+S ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_keys_cb_MoveImg() As String
        Get
            Return ResourceManager.GetString("Settings_keys_cb_MoveImg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Bilder mit Tasten verschieben ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_keys_lbl_MoveImg() As String
        Get
            Return ResourceManager.GetString("Settings_keys_lbl_MoveImg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update() As String
        Get
            Return ResourceManager.GetString("Update", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_btn_update() As String
        Get
            Return ResourceManager.GetString("Update_btn_update", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Changelog ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_lbl_changelog() As String
        Get
            Return ResourceManager.GetString("Update_lbl_changelog", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Deine Version: ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_lbl_LocalVersion() As String
        Get
            Return ResourceManager.GetString("Update_lbl_LocalVersion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Aktuellste Version: ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_lbl_NewestVersion() As String
        Get
            Return ResourceManager.GetString("Update_lbl_NewestVersion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Keine Verbindung zu den Update-Servern möglich. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress_1() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress-1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Suche nach Updates... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress0() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress0", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Du benutzt bereits die neuste Version! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress1() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Lade Details der neuen Version... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress2() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress2", resourceCulture)
        End Get
    End Property
End Class
