'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
'-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
'''<summary>
'''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class strings_cs_CZ
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Raffy_Timelapse.strings_cs_CZ", GetType(strings_cs_CZ).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Všechny snímky ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_AllPicturefiles() As String
        Get
            Return ResourceManager.GetString("_General_AllPicturefiles", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Zrušit ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_cancel() As String
        Get
            Return ResourceManager.GetString("_General_cancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Uzavřít ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_close() As String
        Get
            Return ResourceManager.GetString("_General_close", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Chyba ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_error() As String
        Get
            Return ResourceManager.GetString("_General_error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die soubor ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_file() As String
        Get
            Return ResourceManager.GetString("_General_file", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die soubory ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_files() As String
        Get
            Return ResourceManager.GetString("_General_files", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Informace ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_info() As String
        Get
            Return ResourceManager.GetString("_General_info", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Česky ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_cs_CZ() As String
        Get
            Return ResourceManager.GetString("_General_language_cs_CZ", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_de_DE() As String
        Get
            Return ResourceManager.GetString("_General_language_de_DE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_en_US() As String
        Get
            Return ResourceManager.GetString("_General_language_en_US", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Francouzština ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_fr_FR() As String
        Get
            Return ResourceManager.GetString("_General_language_fr_FR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Portuguese ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_pt_PT() As String
        Get
            Return ResourceManager.GetString("_General_language_pt_PT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_ok() As String
        Get
            Return ResourceManager.GetString("_General_ok", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Prosím čekej... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_wait() As String
        Get
            Return ResourceManager.GetString("_General_wait", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Varování ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_warning() As String
        Get
            Return ResourceManager.GetString("_General_warning", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die O ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property About() As String
        Get
            Return ResourceManager.GetString("About", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Verze: ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property About_version() As String
        Get
            Return ResourceManager.GetString("About_version", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Kredity ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Credits() As String
        Get
            Return ResourceManager.GetString("Credits", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Překlady ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Credits_lbl_translators_head() As String
        Get
            Return ResourceManager.GetString("Credits_lbl_translators_head", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Budete přesměrováni na stránky tvorby obsahu. Chcete pokračovat? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Credits_link() As String
        Get
            Return ResourceManager.GetString("Credits_link", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help() As String
        Get
            Return ResourceManager.GetString("Help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Přímý kontakt ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_gb_contact() As String
        Get
            Return ResourceManager.GetString("Help_gb_contact", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Online podpora ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_gb_support() As String
        Get
            Return ResourceManager.GetString("Help_gb_support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Wiki ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_gb_wiki() As String
        Get
            Return ResourceManager.GetString("Help_gb_wiki", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Prosíme kontaktujte nás přes e-mail POUZE v případě, že náš systém nezná váš požadavek. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_lbl_contact() As String
        Get
            Return ResourceManager.GetString("Help_lbl_contact", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Preferovaná cesta dostat podporu pro Raffy Timelapse je vytvoření tiketu online na GitHub. Máme různé systémy tiket pro různé požadavky.
    '''
    '''Prosím vytvořte tiket jestliže najdete chybu, máte požadavek na novou funkci nebo máte jinou otázku týkající se Raffy Timelapse! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_lbl_support() As String
        Get
            Return ResourceManager.GetString("Help_lbl_support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Podívejte se, jak začít s Raffy Timelapse na Wiki online. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_lbl_wiki() As String
        Get
            Return ResourceManager.GetString("Help_lbl_wiki", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Vytvoření tiketu ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_llbl_support() As String
        Get
            Return ResourceManager.GetString("Help_llbl_support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse Wiki ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_llbl_wiki() As String
        Get
            Return ResourceManager.GetString("Help_llbl_wiki", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importování Snímků ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Import() As String
        Get
            Return ResourceManager.GetString("Import", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importování snímku ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Import_lbl_progress1() As String
        Get
            Return ResourceManager.GetString("Import_lbl_progress1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die od ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Import_lbl_progress2() As String
        Get
            Return ResourceManager.GetString("Import_lbl_progress2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importování snímků... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ImportProgressInfo() As String
        Get
            Return ResourceManager.GetString("ImportProgressInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Smazat ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_del() As String
        Get
            Return ResourceManager.GetString("Main_btn_del", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Prohledávat ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_drop() As String
        Get
            Return ResourceManager.GetString("Main_btn_drop", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Dolů ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_MoveDwn() As String
        Get
            Return ResourceManager.GetString("Main_btn_MoveDwn", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Nahoru ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_MoveUp() As String
        Get
            Return ResourceManager.GetString("Main_btn_MoveUp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Výběr ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_MultiSelect() As String
        Get
            Return ResourceManager.GetString("Main_btn_MultiSelect", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_start() As String
        Get
            Return ResourceManager.GetString("Main_btn_start", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Chyba: Timelapse nemůže být úspěšně exportiváno. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress__1() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_-1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Chyba: Problém s pamětí. Zkuste použít menší rozlišení. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress__2() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_-2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Počítač se připravuje... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_1() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Kopírování souborů... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_10() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_10", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Hotovo! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_100() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_100", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Film se vytváří, může to chvíli trvat... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_40() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_40", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Film se konvertuje, může to chvíli trvat... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_75() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_75", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Editovat snímky ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_gb_PictureEdit() As String
        Get
            Return ResourceManager.GetString("Main_gb_PictureEdit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Všechny snímky musí mít stejné rozlišení jako první importovaný ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_DifferentResolution() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_DifferentResolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Chyba pro {0}:  ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_error() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Nic neimportováno ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_NoPictures() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_NoPictures", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Tento typ není podporován ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_UnsupportedFiletype() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_UnsupportedFiletype", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Přetáhni snímky sem nebo je vyber ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_lbl_drop() As String
        Get
            Return ResourceManager.GetString("Main_lbl_drop", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Náhled ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_lbl_preview() As String
        Get
            Return ResourceManager.GetString("Main_lbl_preview", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Timeline ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_lbl_timeline() As String
        Get
            Return ResourceManager.GetString("Main_lbl_timeline", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Okolo ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about() As String
        Get
            Return ResourceManager.GetString("Main_ms_about", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die O programu ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_about() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_about", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Kredity ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_credits() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_credits", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Nastavení ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_settings() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_settings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_update() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_update", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Soubor ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file() As String
        Get
            Return ResourceManager.GetString("Main_ms_file", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_exit() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_exit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Import snímků ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_import() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_import", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Nový ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_new() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_new", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Projekt... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_new_project() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_new_project", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Window... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_new_window() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_new_window", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_help() As String
        Get
            Return ResourceManager.GetString("Main_ms_help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_help_help() As String
        Get
            Return ResourceManager.GetString("Main_ms_help_help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Podpoř nás ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_help_SupportUs() As String
        Get
            Return ResourceManager.GetString("Main_ms_help_SupportUs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Chcete opravdu zavřít toto okno? Všechny neuložené změny budou ztraceny. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_closing() As String
        Get
            Return ResourceManager.GetString("Main_msg_closing", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse nemůže na vašem počítači najít &apos;FFmpeg.exe&apos;, který je nutný pro běh tohoto programu. Chcete tento chybějící soubor stáhnout? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_ffmpeg() As String
        Get
            Return ResourceManager.GetString("Main_msg_ffmpeg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Jste si jistí, že chcete smazat všechny vybrané snímky? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_MultiDelete() As String
        Get
            Return ResourceManager.GetString("Main_msg_MultiDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Chcete opravdu vytvořit nový projekt? Všechny neuložené změny budou ztraceny. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_NewProject() As String
        Get
            Return ResourceManager.GetString("Main_msg_NewProject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Jste si jistí, že chcete smazat snímek [%1]? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_SingleDelete() As String
        Get
            Return ResourceManager.GetString("Main_msg_SingleDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Pomož nám s překladem ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation() As String
        Get
            Return ResourceManager.GetString("Participation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse je free program and půjde vždy touto cestou. Nechceme vás žádat o peníze. Ale jestli nás chcete podpořit, a mluvíte jazykem, kterým my nemluvíme, prosím pomožte nám přeložit tento program do jiných jazyků. Je to zdarma a velmi jednoduché! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation_lbl_desc() As String
        Get
            Return ResourceManager.GetString("Participation_lbl_desc", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Přelož aplikaci ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation_lbl_head() As String
        Get
            Return ResourceManager.GetString("Participation_lbl_head", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Překládej! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation_lbl_link() As String
        Get
            Return ResourceManager.GetString("Participation_lbl_link", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Proces ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProgressInfo() As String
        Get
            Return ResourceManager.GetString("ProgressInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Podívejte do logu... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProgressInfo_lbl_errorlog() As String
        Get
            Return ResourceManager.GetString("ProgressInfo_lbl_errorlog", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Nastavení projektu ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings() As String
        Get
            Return ResourceManager.GetString("ProjectSettings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Prohledávat ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_btn_browse() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_btn_browse", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Vysoká kvalita, pomalý proces ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_quality_hq() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_quality_hq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Nízká kvalita, rychlý proces ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_quality_lq() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_quality_lq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Střední kvalita i rychlost ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_quality_mq() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_quality_mq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Jako vstup ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_resolution_OriginalResolution() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_resolution_OriginalResolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Pokročilý režim... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_advancedMode_advanced() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_advancedMode_advanced", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Jednoduchý režim ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_advancedMode_simple() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_advancedMode_simple", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Snímky za sekundu (FPS) ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_fps() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_fps", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Kvalita/Rychlost procesu ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_quality() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_quality", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Rozlišení ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_resolution() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_resolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Ulož jako... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_SaveTo() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_SaveTo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Vypraná cesta neexistuje. Je cesta pro export správná? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_InvalidPath() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_InvalidPath", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Prosím vyber Snímky za sekundu (FPS). ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_NoFps() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_NoFps", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Prosím vyber rozlišení. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_NoResolution() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_NoResolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Prosím vyber nastavení Kvalita / Rychlost procesu. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_quality() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_quality", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importovaní snímky mají menší rozlišení než nastavený export videa. Prosím vyber jiné rozlišení. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_undersize() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_undersize", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Nastavení ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings() As String
        Get
            Return ResourceManager.GetString("Settings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_gb_general() As String
        Get
            Return ResourceManager.GetString("Settings_gb_general", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Přiřazení kláves ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_gb_keys() As String
        Get
            Return ResourceManager.GetString("Settings_gb_keys", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Kontrola aktualizací při startu ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_general_cb_AutoUpdate() As String
        Get
            Return ResourceManager.GetString("Settings_general_cb_AutoUpdate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Jazyk ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_general_lbl_language() As String
        Get
            Return ResourceManager.GetString("Settings_general_lbl_language", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die 2+8 (Numpad), W+S,Z+S ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_keys_cb_MoveImg() As String
        Get
            Return ResourceManager.GetString("Settings_keys_cb_MoveImg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Pohyb snímků nahoru a dolů ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_keys_lbl_MoveImg() As String
        Get
            Return ResourceManager.GetString("Settings_keys_lbl_MoveImg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Aktualizovat ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update() As String
        Get
            Return ResourceManager.GetString("Update", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Aktualizovat ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_btn_update() As String
        Get
            Return ResourceManager.GetString("Update_btn_update", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Změnový záznam ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_lbl_changelog() As String
        Get
            Return ResourceManager.GetString("Update_lbl_changelog", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Tato verze: ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_lbl_LocalVersion() As String
        Get
            Return ResourceManager.GetString("Update_lbl_LocalVersion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Polsední verze: ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_lbl_NewestVersion() As String
        Get
            Return ResourceManager.GetString("Update_lbl_NewestVersion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse bude z důvodu instalování update automaticky ukončeno. Všechny neuložené změny budou ztraceny. Chcete pokračovat? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_msg_close() As String
        Get
            Return ResourceManager.GetString("Update_msg_close", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Program &apos;Raffy Timelapse Updater&apos; nebyl na vašem pořítači nalezen. Prosím stáhněte si poslední verzi manuálně. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_msg_UpdaterNotFound() As String
        Get
            Return ResourceManager.GetString("Update_msg_UpdaterNotFound", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Není spojení k aktualizačnímu serveru. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress_1() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress-1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Hledání nové verze... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress0() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress0", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Fakt používáte poslední verzi! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress1() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Nahrávání detailů nové verze... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress2() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress2", resourceCulture)
        End Get
    End Property
End Class
