'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
'-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
'''<summary>
'''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class strings_fr_FR
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Raffy_Timelapse.strings_fr_FR", GetType(strings_fr_FR).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Tous les fichiers images ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_AllPicturefiles() As String
        Get
            Return ResourceManager.GetString("_General_AllPicturefiles", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Annuler ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_cancel() As String
        Get
            Return ResourceManager.GetString("_General_cancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Fermer ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_close() As String
        Get
            Return ResourceManager.GetString("_General_close", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Erreur ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_error() As String
        Get
            Return ResourceManager.GetString("_General_error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die fichier ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_file() As String
        Get
            Return ResourceManager.GetString("_General_file", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die fichiers ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_files() As String
        Get
            Return ResourceManager.GetString("_General_files", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_info() As String
        Get
            Return ResourceManager.GetString("_General_info", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Tchèque ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_cs_CZ() As String
        Get
            Return ResourceManager.GetString("_General_language_cs_CZ", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Allemand ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_de_DE() As String
        Get
            Return ResourceManager.GetString("_General_language_de_DE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Anglais ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_en_US() As String
        Get
            Return ResourceManager.GetString("_General_language_en_US", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Français ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_fr_FR() As String
        Get
            Return ResourceManager.GetString("_General_language_fr_FR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Portugais ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_pt_PT() As String
        Get
            Return ResourceManager.GetString("_General_language_pt_PT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_ok() As String
        Get
            Return ResourceManager.GetString("_General_ok", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Merci de patienter... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_wait() As String
        Get
            Return ResourceManager.GetString("_General_wait", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Attention ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_warning() As String
        Get
            Return ResourceManager.GetString("_General_warning", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die A propos ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property About() As String
        Get
            Return ResourceManager.GetString("About", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Version : ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property About_version() As String
        Get
            Return ResourceManager.GetString("About_version", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Crédits ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Credits() As String
        Get
            Return ResourceManager.GetString("Credits", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Traducteurs ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Credits_lbl_translators_head() As String
        Get
            Return ResourceManager.GetString("Credits_lbl_translators_head", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Vous aller être redirigé faire le site du créateur. Voulez-vous continuer ? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Credits_link() As String
        Get
            Return ResourceManager.GetString("Credits_link", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Aide ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help() As String
        Get
            Return ResourceManager.GetString("Help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Contact direct ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_gb_contact() As String
        Get
            Return ResourceManager.GetString("Help_gb_contact", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Support en ligne ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_gb_support() As String
        Get
            Return ResourceManager.GetString("Help_gb_support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Wiki ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_gb_wiki() As String
        Get
            Return ResourceManager.GetString("Help_gb_wiki", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Merci de nous contacter uniquement par e-mail si le system de ticket ne correspond pas à votre demande. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_lbl_contact() As String
        Get
            Return ResourceManager.GetString("Help_lbl_contact", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Le meilleur moyen d&apos;obtenir de l&apos;aide sur Raffy Timpelapse est d&apos;ouvrir un ticket sur GitHub. Nous avons differents types de ticket en fonctions de ce que vous cherchez.
    '''
    '''Merci de nous prévenir en cas de bug en faisant un ticket, si vous souahitez de nouvelle fonctionnalités, ou si vous avez d&apos;autres questions sur Raffy Timelapse ! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_lbl_support() As String
        Get
            Return ResourceManager.GetString("Help_lbl_support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Apprendre à utiliser Raffy Timelapse sur notre Wiki en ligne. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_lbl_wiki() As String
        Get
            Return ResourceManager.GetString("Help_lbl_wiki", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Ouvrir un ticket ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_llbl_support() As String
        Get
            Return ResourceManager.GetString("Help_llbl_support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse Wiki ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_llbl_wiki() As String
        Get
            Return ResourceManager.GetString("Help_llbl_wiki", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importation des images ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Import() As String
        Get
            Return ResourceManager.GetString("Import", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importation de l&apos;image ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Import_lbl_progress1() As String
        Get
            Return ResourceManager.GetString("Import_lbl_progress1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die de ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Import_lbl_progress2() As String
        Get
            Return ResourceManager.GetString("Import_lbl_progress2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importation des images... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ImportProgressInfo() As String
        Get
            Return ResourceManager.GetString("ImportProgressInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Suppr. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_del() As String
        Get
            Return ResourceManager.GetString("Main_btn_del", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Choisir ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_drop() As String
        Get
            Return ResourceManager.GetString("Main_btn_drop", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Descendre ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_MoveDwn() As String
        Get
            Return ResourceManager.GetString("Main_btn_MoveDwn", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Monter ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_MoveUp() As String
        Get
            Return ResourceManager.GetString("Main_btn_MoveUp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Séléction Multiple ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_MultiSelect() As String
        Get
            Return ResourceManager.GetString("Main_btn_MultiSelect", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Départ ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_start() As String
        Get
            Return ResourceManager.GetString("Main_btn_start", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Erreur : le timelapse n&apos;as pas pût être exporté. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress__1() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_-1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Erreur : Impossible d&apos;allouer la mémoire. Essayez d&apos;utiliser un plus faible résolutions. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress__2() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_-2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die L&apos;ordinateur est en cours de préparation... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_1() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Copie des fichiers... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_10() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_10", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Terminé! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_100() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_100", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Création de la vidéo, cela peut prendre du temps... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_40() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_40", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Conversion de la vidéo, cela peut prendre du temps... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_75() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_75", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Modifier l&apos;image ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_gb_PictureEdit() As String
        Get
            Return ResourceManager.GetString("Main_gb_PictureEdit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Toutes les images doivent avoir la même résolution que la première image importées ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_DifferentResolution() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_DifferentResolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Erreur pour {0} :  ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_error() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Aucune images importé ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_NoPictures() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_NoPictures", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Type de fichiers non pris en charge ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_UnsupportedFiletype() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_UnsupportedFiletype", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Déposez votre image ici ou choisissez un fichier ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_lbl_drop() As String
        Get
            Return ResourceManager.GetString("Main_lbl_drop", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Aperçu ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_lbl_preview() As String
        Get
            Return ResourceManager.GetString("Main_lbl_preview", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Timeline ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_lbl_timeline() As String
        Get
            Return ResourceManager.GetString("Main_lbl_timeline", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Info. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about() As String
        Get
            Return ResourceManager.GetString("Main_ms_about", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Information du logiciel ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_about() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_about", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Crédits ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_credits() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_credits", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Paramètres ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_settings() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_settings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Mise à Jour ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_update() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_update", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Fichier ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file() As String
        Get
            Return ResourceManager.GetString("Main_ms_file", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Sortir ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_exit() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_exit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importer les images ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_import() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_import", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Nouveau ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_new() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_new", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Projet... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_new_project() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_new_project", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Fenêtre... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_new_window() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_new_window", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Aide ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_help() As String
        Get
            Return ResourceManager.GetString("Main_ms_help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Aide ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_help_help() As String
        Get
            Return ResourceManager.GetString("Main_ms_help_help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Faire un don ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_help_SupportUs() As String
        Get
            Return ResourceManager.GetString("Main_ms_help_SupportUs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Voulez-vous vraiment fermer la fenêtre ? Les changement non sauvegardés seront perdus. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_closing() As String
        Get
            Return ResourceManager.GetString("Main_msg_closing", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse n&apos;a pas pu trouver &apos;FFmpeg.exe&apos; sur votre ordinateur, qui est nécessaire pour utiliser ce programme. Souhaitez-vous télécharger le fichier manquant ? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_ffmpeg() As String
        Get
            Return ResourceManager.GetString("Main_msg_ffmpeg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Êtes-vous sûr de vouloir supprimer les images séléctionnées ? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_MultiDelete() As String
        Get
            Return ResourceManager.GetString("Main_msg_MultiDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Voulez-vous vraiement créer un nouveau projet ? Les changement non sauvegardés seront perdus. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_NewProject() As String
        Get
            Return ResourceManager.GetString("Main_msg_NewProject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Êtes-vous sûr de vouloir supprimer l&apos;images [%1] ? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_SingleDelete() As String
        Get
            Return ResourceManager.GetString("Main_msg_SingleDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Participer à la traduction ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation() As String
        Get
            Return ResourceManager.GetString("Participation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse est un logiciel gratuit qui le restera toujours. Nous ne voulons pas vous demander de dons non plus. Mais si vous souhaitez nous aider, ou que vous parlez une langue que nous ne parlons pas, alors merci d&apos;avance de nous aider à traduire notre logiciel dans d&apos;autres langues. C&apos;est gratuit et simple ! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation_lbl_desc() As String
        Get
            Return ResourceManager.GetString("Participation_lbl_desc", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Traduire l&apos;application ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation_lbl_head() As String
        Get
            Return ResourceManager.GetString("Participation_lbl_head", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Traduire maintenant ! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation_lbl_link() As String
        Get
            Return ResourceManager.GetString("Participation_lbl_link", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Traitement ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProgressInfo() As String
        Get
            Return ResourceManager.GetString("ProgressInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Voir les journaux... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProgressInfo_lbl_errorlog() As String
        Get
            Return ResourceManager.GetString("ProgressInfo_lbl_errorlog", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Paramètres du projet ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings() As String
        Get
            Return ResourceManager.GetString("ProjectSettings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Choisir un fichier ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_btn_browse() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_btn_browse", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Haute qualité, vitesse de traitement lente ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_quality_hq() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_quality_hq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Basse qualité, haute vitesse de traitement ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_quality_lq() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_quality_lq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Moyenne qualité et vitesse de traitement ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_quality_mq() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_quality_mq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Comme en entrée ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_resolution_OriginalResolution() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_resolution_OriginalResolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Mode avancé... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_advancedMode_advanced() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_advancedMode_advanced", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Mode simple... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_advancedMode_simple() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_advancedMode_simple", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Frame par secondes (FPS) ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_fps() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_fps", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Qualité/Vitesse de traitement ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_quality() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_quality", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Résolution ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_resolution() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_resolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Enregistrer sous... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_SaveTo() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_SaveTo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Le dossier spécifié n&apos;existe pas. Merci de verifier que votre dossier éxiste. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_InvalidPath() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_InvalidPath", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Merci de séléctionner le nombre d&apos;images pas secondes (FPS). ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_NoFps() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_NoFps", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Merci de séléctionner une résolution. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_NoResolution() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_NoResolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Merci de séléctionner une proportion entre qualité et vitesse de traitement. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_quality() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_quality", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die L&apos;image importé a un résolution plus basse que la résolution d&apos;export de la vidéo. Veuillez choisir une autre résolution. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_undersize() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_undersize", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Paramètres ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings() As String
        Get
            Return ResourceManager.GetString("Settings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Général ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_gb_general() As String
        Get
            Return ResourceManager.GetString("Settings_gb_general", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Assignement de la touche ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_gb_keys() As String
        Get
            Return ResourceManager.GetString("Settings_gb_keys", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Verifier les mise à jour au démarrage ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_general_cb_AutoUpdate() As String
        Get
            Return ResourceManager.GetString("Settings_general_cb_AutoUpdate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Langue ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_general_lbl_language() As String
        Get
            Return ResourceManager.GetString("Settings_general_lbl_language", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die 2+8 (Clavier numérique), W+S,Z+S ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_keys_cb_MoveImg() As String
        Get
            Return ResourceManager.GetString("Settings_keys_cb_MoveImg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Déplacer l&apos;image vers le haut/bas ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_keys_lbl_MoveImg() As String
        Get
            Return ResourceManager.GetString("Settings_keys_lbl_MoveImg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Mettre à jour ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update() As String
        Get
            Return ResourceManager.GetString("Update", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Mettre à jour ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_btn_update() As String
        Get
            Return ResourceManager.GetString("Update_btn_update", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Journal des modifications ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_lbl_changelog() As String
        Get
            Return ResourceManager.GetString("Update_lbl_changelog", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Cette Version : ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_lbl_LocalVersion() As String
        Get
            Return ResourceManager.GetString("Update_lbl_LocalVersion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Dernière Version : ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_lbl_NewestVersion() As String
        Get
            Return ResourceManager.GetString("Update_lbl_NewestVersion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse vas se fermer automatiquement pour effectuer les mise à jour. Tous les changements non enregistré seront perdu. Voulez-vous continuer ? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_msg_close() As String
        Get
            Return ResourceManager.GetString("Update_msg_close", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Le dispositif de mise à jour est introuvable. Merci de télécharger la dérnière version en ligne. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_msg_UpdaterNotFound() As String
        Get
            Return ResourceManager.GetString("Update_msg_UpdaterNotFound", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Impossible de se connecter au serveur de mise à jour. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress_1() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress-1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Recherche de mise à jour... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress0() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress0", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Vous disposez déjà de la dernière Version ! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress1() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Chargement des détails de la nouvelle version... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress2() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress2", resourceCulture)
        End Get
    End Property
End Class
