'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
'-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
'''<summary>
'''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class strings_pt_PT
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Raffy_Timelapse.strings_pt_PT", GetType(strings_pt_PT).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Todos os tipos de imagem ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_AllPicturefiles() As String
        Get
            Return ResourceManager.GetString("_General_AllPicturefiles", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Cancelar ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_cancel() As String
        Get
            Return ResourceManager.GetString("_General_cancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Fechar ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_close() As String
        Get
            Return ResourceManager.GetString("_General_close", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Erro ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_error() As String
        Get
            Return ResourceManager.GetString("_General_error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Ficheiro ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_file() As String
        Get
            Return ResourceManager.GetString("_General_file", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Ficheiros ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_files() As String
        Get
            Return ResourceManager.GetString("_General_files", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Informação ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_info() As String
        Get
            Return ResourceManager.GetString("_General_info", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Checo ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_cs_CZ() As String
        Get
            Return ResourceManager.GetString("_General_language_cs_CZ", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Alemão ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_de_DE() As String
        Get
            Return ResourceManager.GetString("_General_language_de_DE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Inglês ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_en_US() As String
        Get
            Return ResourceManager.GetString("_General_language_en_US", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Francês ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_fr_FR() As String
        Get
            Return ResourceManager.GetString("_General_language_fr_FR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Português ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_language_pt_PT() As String
        Get
            Return ResourceManager.GetString("_General_language_pt_PT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_ok() As String
        Get
            Return ResourceManager.GetString("_General_ok", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Aguarde por favor... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_wait() As String
        Get
            Return ResourceManager.GetString("_General_wait", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Aviso ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property _General_warning() As String
        Get
            Return ResourceManager.GetString("_General_warning", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Sobre ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property About() As String
        Get
            Return ResourceManager.GetString("About", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Versão: ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property About_version() As String
        Get
            Return ResourceManager.GetString("About_version", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Créditos ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Credits() As String
        Get
            Return ResourceManager.GetString("Credits", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Credits_lbl_translators_head() As String
        Get
            Return ResourceManager.GetString("Credits_lbl_translators_head", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Você está sendo redireccionado para o site do criador do conteúdo. Você gostaria de continuar? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Credits_link() As String
        Get
            Return ResourceManager.GetString("Credits_link", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Ajuda ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help() As String
        Get
            Return ResourceManager.GetString("Help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Contacto Direto ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_gb_contact() As String
        Get
            Return ResourceManager.GetString("Help_gb_contact", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Suporte Online ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_gb_support() As String
        Get
            Return ResourceManager.GetString("Help_gb_support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Wiki ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_gb_wiki() As String
        Get
            Return ResourceManager.GetString("Help_gb_wiki", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Por favor, apenas entre em contacto connosco via e-mail se o sistema de ingressos não atender aos seus requisitos de solicitação. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_lbl_contact() As String
        Get
            Return ResourceManager.GetString("Help_lbl_contact", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die A maneira preferida de obter suporte para o Raffy Timelapse é criar um ticket on-line no GitHub. Temos diferentes sistemas de tickets para diferentes requisitos.
    '''
    '''Por favor, crie um ticket se você encontrou um bug, tenha um pedido de recurso ou tenha alguma outra dúvida sobre Raffy Timelapse! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_lbl_support() As String
        Get
            Return ResourceManager.GetString("Help_lbl_support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Saiba como começar com Raffy Timelapse no nosso Wiki on-line. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_lbl_wiki() As String
        Get
            Return ResourceManager.GetString("Help_lbl_wiki", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Criar um pedido ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_llbl_support() As String
        Get
            Return ResourceManager.GetString("Help_llbl_support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse Wiki ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Help_llbl_wiki() As String
        Get
            Return ResourceManager.GetString("Help_llbl_wiki", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die A importar imagens ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Import() As String
        Get
            Return ResourceManager.GetString("Import", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die A importar imagem ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Import_lbl_progress1() As String
        Get
            Return ResourceManager.GetString("Import_lbl_progress1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die of ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Import_lbl_progress2() As String
        Get
            Return ResourceManager.GetString("Import_lbl_progress2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importando Imagens... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ImportProgressInfo() As String
        Get
            Return ResourceManager.GetString("ImportProgressInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Eliminar ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_del() As String
        Get
            Return ResourceManager.GetString("Main_btn_del", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Procurar ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_drop() As String
        Get
            Return ResourceManager.GetString("Main_btn_drop", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Descer ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_MoveDwn() As String
        Get
            Return ResourceManager.GetString("Main_btn_MoveDwn", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Subir ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_MoveUp() As String
        Get
            Return ResourceManager.GetString("Main_btn_MoveUp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Multi Seleção ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_MultiSelect() As String
        Get
            Return ResourceManager.GetString("Main_btn_MultiSelect", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Iniciar ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_btn_start() As String
        Get
            Return ResourceManager.GetString("Main_btn_start", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress__1() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_-1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress__2() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_-2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die O Computador está a ser preparado... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_1() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die A copiar ficheiros ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_10() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_10", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Terminado! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_100() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_100", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die O Video está a ser criado,isto pode demorar algum tempo... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_40() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_40", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die O Vídeo está a ser convertido, isto pode demorar algum tempo... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_bw_Rendering_Progress_75() As String
        Get
            Return ResourceManager.GetString("Main_bw_Rendering_Progress_75", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Editar Imagem ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_gb_PictureEdit() As String
        Get
            Return ResourceManager.GetString("Main_gb_PictureEdit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Todas as imagens têm de ter a mesma resolução que a primeira imagem importada ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_DifferentResolution() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_DifferentResolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_error() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Sem imagens importadas ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_NoPictures() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_NoPictures", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Este tipo de ficheiro não é suportado ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ImportFiles_msg_UnsupportedFiletype() As String
        Get
            Return ResourceManager.GetString("Main_ImportFiles_msg_UnsupportedFiletype", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Largar aqui as imagens ou procurar por ficheiros ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_lbl_drop() As String
        Get
            Return ResourceManager.GetString("Main_lbl_drop", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Pré-Visualizar ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_lbl_preview() As String
        Get
            Return ResourceManager.GetString("Main_lbl_preview", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Linha de Tempo ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_lbl_timeline() As String
        Get
            Return ResourceManager.GetString("Main_lbl_timeline", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Sobre ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about() As String
        Get
            Return ResourceManager.GetString("Main_ms_about", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Sobre o Software ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_about() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_about", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Créditos ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_credits() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_credits", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Definições ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_settings() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_settings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Atualização ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_about_update() As String
        Get
            Return ResourceManager.GetString("Main_ms_about_update", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Ficheiro ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file() As String
        Get
            Return ResourceManager.GetString("Main_ms_file", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Sair ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_exit() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_exit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Importar imagens ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_import() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_import", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Novo ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_new() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_new", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Projeto... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_new_project() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_new_project", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Janela... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_file_new_window() As String
        Get
            Return ResourceManager.GetString("Main_ms_file_new_window", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Ajuda ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_help() As String
        Get
            Return ResourceManager.GetString("Main_ms_help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Ajuda ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_help_help() As String
        Get
            Return ResourceManager.GetString("Main_ms_help_help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Dar Contribuição ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_ms_help_SupportUs() As String
        Get
            Return ResourceManager.GetString("Main_ms_help_SupportUs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Você gostaria realmente de fechar esta janela? Todas as alterações não salvas serão perdidas. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_closing() As String
        Get
            Return ResourceManager.GetString("Main_msg_closing", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse não conseguiu encontrar o &apos;FFmpeg.exe&apos; no seu computador, o que é necessário para usar este programa. Gostaria de baixar o arquivo em falta? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_ffmpeg() As String
        Get
            Return ResourceManager.GetString("Main_msg_ffmpeg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Tem a certeza de que quer apagar todas as imagens selecionadas? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_MultiDelete() As String
        Get
            Return ResourceManager.GetString("Main_msg_MultiDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Você gostaria realmente de criar um novo projeto? Todas as alterações não salvas serão perdidas. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_NewProject() As String
        Get
            Return ResourceManager.GetString("Main_msg_NewProject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Tem certeza de que deseja excluir a imagem [% 1]? ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Main_msg_SingleDelete() As String
        Get
            Return ResourceManager.GetString("Main_msg_SingleDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Ajudar a Traduzir ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation() As String
        Get
            Return ResourceManager.GetString("Participation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Raffy Timelapse é um programa gratuito e será sempre assim. Nós não queremos pedir-lhe dinheiro também. Mas se você quiser nos apoiar e falar um idioma que não falamos, ajude-nos a traduzir esse programa para outros idiomas. É grátis e muito simples! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation_lbl_desc() As String
        Get
            Return ResourceManager.GetString("Participation_lbl_desc", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Traduzir este Programa ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation_lbl_head() As String
        Get
            Return ResourceManager.GetString("Participation_lbl_head", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Traduzir agora! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Participation_lbl_link() As String
        Get
            Return ResourceManager.GetString("Participation_lbl_link", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die A processar ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProgressInfo() As String
        Get
            Return ResourceManager.GetString("ProgressInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProgressInfo_lbl_errorlog() As String
        Get
            Return ResourceManager.GetString("ProgressInfo_lbl_errorlog", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Definições do Projeto ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings() As String
        Get
            Return ResourceManager.GetString("ProjectSettings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Procurar ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_btn_browse() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_btn_browse", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Alta qualidade, processamento lento ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_quality_hq() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_quality_hq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Baixa qualidade, processamento rápido ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_quality_lq() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_quality_lq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Média qualidade e velocidade de processamento ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_quality_mq() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_quality_mq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Igual a Entrada ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_cb_resolution_OriginalResolution() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_cb_resolution_OriginalResolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Modo avançado... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_advancedMode_advanced() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_advancedMode_advanced", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Modo simples... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_advancedMode_simple() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_advancedMode_simple", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Frames por Segundo (FPS) ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_fps() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_fps", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Qualidade/Velocidade de Processamento ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_quality() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_quality", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Resolução ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_resolution() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_resolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Guardar em... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_lbl_SaveTo() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_lbl_SaveTo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die O caminho especificado não existe. Por favor, verifique se o seu caminho de exportação está correto. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_InvalidPath() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_InvalidPath", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Por favor, selecione os frames por segundo (FPS). ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_NoFps() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_NoFps", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Por favor selecione uma resolução. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_NoResolution() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_NoResolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Por favor, selecione uma proporção entre qualidade e velocidade de processamento. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_quality() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_quality", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die As imagens importadas têm uma resolução menor que a resolução de exportação de vídeo. Por favor, selecione outra resolução. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property ProjectSettings_msg_undersize() As String
        Get
            Return ResourceManager.GetString("ProjectSettings_msg_undersize", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Configurações ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings() As String
        Get
            Return ResourceManager.GetString("Settings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Geral ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_gb_general() As String
        Get
            Return ResourceManager.GetString("Settings_gb_general", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Atribuição de chave ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_gb_keys() As String
        Get
            Return ResourceManager.GetString("Settings_gb_keys", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Procurar por actualizações na inicialização ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_general_cb_AutoUpdate() As String
        Get
            Return ResourceManager.GetString("Settings_general_cb_AutoUpdate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Idioma ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_general_lbl_language() As String
        Get
            Return ResourceManager.GetString("Settings_general_lbl_language", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die 2+8 (Teclado Numerico),W+S,Z+S ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_keys_cb_MoveImg() As String
        Get
            Return ResourceManager.GetString("Settings_keys_cb_MoveImg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Mover imagens para cima e para baixo ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Settings_keys_lbl_MoveImg() As String
        Get
            Return ResourceManager.GetString("Settings_keys_lbl_MoveImg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Atualização ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update() As String
        Get
            Return ResourceManager.GetString("Update", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Atualização ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_btn_update() As String
        Get
            Return ResourceManager.GetString("Update_btn_update", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Registo de Alterações ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_lbl_changelog() As String
        Get
            Return ResourceManager.GetString("Update_lbl_changelog", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die A sua Versão: ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_lbl_LocalVersion() As String
        Get
            Return ResourceManager.GetString("Update_lbl_LocalVersion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Ultima Versão: ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_lbl_NewestVersion() As String
        Get
            Return ResourceManager.GetString("Update_lbl_NewestVersion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_msg_close() As String
        Get
            Return ResourceManager.GetString("Update_msg_close", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property Update_msg_UpdaterNotFound() As String
        Get
            Return ResourceManager.GetString("Update_msg_UpdaterNotFound", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Sem ligação aos servidores de atualização. ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress_1() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress-1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Procurando por atualizações... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress0() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress0", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die Já está a usar a versão mais recente! ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress1() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Sucht eine lokalisierte Zeichenfolge, die A carregar detalhes da nova versão... ähnelt.
    '''</summary>
    Friend Shared ReadOnly Property UpdateSearch_lbl_progress2() As String
        Get
            Return ResourceManager.GetString("UpdateSearch_lbl_progress2", resourceCulture)
        End Get
    End Property
End Class
